apriltag_node:
    ros__parameters:
        image_transport: raw    # image format
        family: 36h11           # tag family name
        size: 0.12065            # tag edge size in meter
        max_hamming: 0          # maximum allowed hamming distance (corrected bits)
        z_up: true              # rotate about x-axis to have Z pointing upwards

        # see "apriltag.h" 'struct apriltag_detector' for more documentation on these optional parameters
        # detector:
        #     threads: 1          # number of threads
        #     decimate: 2.0       # decimate resolution for quad detection
        #     blur: 0.0           # sigma of Gaussian blur for quad detection
        #     refine: 1        # snap to strong gradients
        #     sharpening: 0.25    # sharpening of decoded images
        #     debug: 0        # write additional debugging images to current working directory
        
        # # optional list of tags
        # tag:
        #     ids: [1, 2, 3]
        #     frames: [top_left, top_right, bottom_left] # Corresponding to position on whiteboard
        #     sizes: [0.1524, 0.1524, 0.1524]